apiVersion: v2
name: kamaji-console
description: Kamaji deploys and operates Kubernetes at scale with a fraction of the operational burden. This chart install a console for Kamaji.
home: https://github.com/clastix/kamaji-console
icon: https://github.com/clastix/kamaji-console/raw/main/.github/images/icon.png
sources:
- https://github.com/clastix/kamaji-console
annotations:
  catalog.cattle.io/certified: partner
  catalog.cattle.io/release-name: kamaji-console
  catalog.cattle.io/display-name: Kamaji Console
kubeVersion: ">=1.21.0-0"
maintainers:
- email: dario@tranchitella.eu
  name: Dario Tranchitella
- email: me@bsctl.io
  name: Adriano Pezzuto
# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.0.3

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "v0.0.1"
