apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kamaji-console
rules:
- apiGroups:
  - '*'
  resources:
  - namespaces
  - deployments
  - replicasets
  - services
  - pods
  - secrets
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kamaji.clastix.io
  resources:
  - tenantcontrolplanes
  - datastores
  verbs:
  - '*'
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kamaji-console
  namespace: kamaji-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kamaji-console
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kamaji-console
subjects:
- namespace: kamaji-system 
  kind: ServiceAccount
  name: kamaji-console
---
apiVersion: v1
kind: Secret
metadata:
  name: kamaji-console
  namespace: kamaji-system
data:
  # URL where the console is accessible, eg. https://localhost/
  NEXTAUTH_URL: #############################################
  # Secret used to sign the browser session
  JWT_SECRET: #########
  # Credentials to access the console
  ADMIN_EMAIL: ##################
  ADMIN_PASSWORD: #########
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kamaji-console
  namespace: kamaji-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kamaji-console
  template:
    metadata:
      labels:
        app: kamaji-console
    spec:
      serviceAccountName: kamaji-console
      containers:
      - image: clastix/kamaji-console:latest
        imagePullPolicy: IfNotPresent
        name: console
        ports:
          - containerPort: 3000
        envFrom:
          - secretRef:
              name: kamaji-console
        resources:
      # create a secret containing token to pull the image from Docker Hub 
      # kubectl -n kamaji-system create secret generic regcred \
      # --from-file=.dockerconfigjson=<path/to/.docker/config.json> \
      # --type=kubernetes.io/dockerconfigjson
      # imagePullSecrets:
      # - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: kamaji-console
  namespace: kamaji-system
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app: kamaji-console


